---
apiVersion: v1
kind: ConfigMap
metadata:
  name: quiz-covid-form-config
data:
  REACT_APP_API_HOST: 'http://localhost:8080'

---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: quiz-covid-form
  name: quiz-covid-form
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quiz-covid-form
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: quiz-covid-form
    spec:
      containers:
        - image: cmpsmarcio/quiz-covid-form:v1
          name: quiz-covid-form
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: quiz-covid-form-config
          resources: {}
          ports:
            - containerPort: 3000
status: {}

---
apiVersion: v1
kind: Service
metadata:
  name: quiz-covid-form
  labels:
    run: quiz-covid-form
spec:
  ports:
    - port: 3000
      targetPort: 3000
      protocol: 'TCP'
  selector:
    app: quiz-covid-form
  type: NodePort
